#!/usr/bin/env bash
echo "organnery-setup" >> $HOME/organnery.log

# set cpu governor to performance
cpufreq-set -r -g performance

# set output to 100% on analogue jack if onboard sound enabled
if cat /boot/config.txt | grep -q dtparam=audio=on; then
    amixer cset numid=1 100%
    amixer cset numid=3 1
fi

# simple automount script
MEDIA=sda1
USERNAME=user

# quit if no usb drive detected
if ! lsblk | grep $MEDIA; then
    echo "usb not connected! quitting" >> $HOME/organnery.log
    exit 0
fi

# mount the usb drive on top of default stops directory
mount /dev/$MEDIA /home/$USERNAME/stops/ -o rw,sync,noatime,noiversion,norelatime
echo "mounted /dev/$MEDIA on /home/$USERNAME/stops/!" >> $HOME/organnery.log

# TODO check mount is done and stops folder accessible or next test will fail

# if usb drive contains no instrument files, copy defaults to it
if [[ ! $(ls /home/$USERNAME/stops/*.ae0) ]]; then

    # copy stops and instrument definitions
    cp -r /usr/share/organnery/data/stops/* /home/$USERNAME/stops/

    # copy the matching presets, overwrite if necessary
    cp /usr/share/organnery/data/file.aeolus-presets /home/$USERNAME/stops/.aeolus-presets
    cp /usr/share/organnery/data/file.aeolus-aparams /home/$USERNAME/stops/.aeolus-aparams

    # copy default config to usb drive to make it user modifiable, if it doesn't exist
    if [ ! -f /home/$USERNAME/stops/organnery.conf ] ; then
      cp /etc/organnery/organnery.conf /home/$USERNAME/stops/organnery.conf
    fi

    # fix permissions
    sudo chown -R $USERNAME:$USERNAME /home/$USERNAME
    sudo chown -R $USERNAME:$USERNAME /home/$USERNAME/.aeolus-*
    sudo chmod -R 644 /home/$USERNAME/*.*
    echo "copied instrument files to /dev/$MEDIA!" >> $HOME/organnery.log

else echo "existing instrument files found on /dev/$MEDIA!" >> $HOME/organnery.log

fi
