#!/usr/bin/env bash
echo "organnery-setup"

# set cpu governor to performance
cpufreq-set -r -g performance

# set output to 100% on analogue jack if onboard sound enabled
if cat /boot/cmdline.txt | grep -q dtparam=audio=on; then
        amixer cset numid=1 100%
        amixer cset numid=3 1
fi

# simple automount script
MEDIA=sda1
USERNAME=user

# quit if no usb drive detected
if ! lsblk | grep $MEDIA; then
	echo "usb not connected! quitting"
	exit 0
fi

# mount the usb drive on top of default stops directory
mount /dev/$MEDIA /home/$USERNAME/stops/ -o rw,sync,noatime,noiversion,norelatime,umask=0000
echo "mounted!"
