#!/usr/bin/env bash

# kill previous
killall --wait aeolus

# find hardware midi ports
cards=$(aconnect -l | grep type=kernel,card | awk -F[\ ,:] '{print $2}')

# start daemon
aeolus -u -S stops -A &
pid=$!

# connect each card to aeolus
for card in $cards; do
    while ! aconnect $card aeolus; do sleep 1; done
done

# wait for aeolus to quit
wait $!

# restart script
/usr/share/organnery/organnery
