#!/usr/bin/env bash
#
# a configuration script to modify system parameters
#

OVERLAYFS_CMDLINE="init=/usr/share/organnery/overlayRoot.sh"

# mount the boot partition RW
mount_boot_rw()
{
        sudo umount /boot
        sudo mount /dev/mmcblk0p1 /boot
}

if [ "$1" = "mount-boot" ]; then

	# mount boot partition RW
	mount_boot_rw
	echo "boot partition now mounted rw" >> /home/user/organnery.log

elif [ "$1" = "overlayfs-check" ]; then

	# check whether overlayfs is enabled for the current boot
	if grep -q "$OVERLAYFS_CMDLINE" /proc/cmdline; then
		echo "overlayfs is enabled for current session" >> /home/user/organnery.log
	else
		echo "overlayfs is disabled for current session" >> /home/user/organnery.log
	fi

	# check whether overlayfs is enabled for the next boot
	if grep -q "$OVERLAYFS_CMDLINE" /boot/cmdline.txt; then
		echo "overlayfs is enabled for the next session" >> /home/user/organnery.log
	else
		echo "overlayfs is disabled for the next session" >> /home/user/organnery.log
	fi

elif [ "$1" = "overlayfs-disable" ]; then

	mount_boot_rw
	sudo sed -i "s; $OVERLAYFS_CMDLINE;;g" /boot/cmdline.txt
	echo "overlayfs disabled for the next session" >> /home/user/organnery.log

elif [ "$1" = "overlayfs-enable" ]; then

	if ! grep -q "$OVERLAYFS_CMDLINE" /boot/cmdline.txt; then
		mount_boot_rw
		CMDLINE=`cat /boot/cmdline.txt`
		echo "$CMDLINE $OVERLAYFS_CMDLINE" | sudo tee /boot/cmdline.txt > /dev/null
	fi
	echo "overlayfs enabled for the next session" >> /home/user/organnery.log

elif [ "$1" = "pisound-disable" ]; then

		# update boot
        mount_boot_rw
        sudo sed -i "s;dtoverlay=pisound;dtparam=audio=on;g" /boot/config.txt

        # update alsa config
        sudo sed -i "s/^PERIOD_SIZE=\"128\"/PERIOD_SIZE=\"1024\"/" $HOME/stops/organnery.conf

        echo "pisound disabled, onboard sound enabled for the next session" >> /home/user/organnery.log
        sudo reboot

elif [ "$1" = "pisound-enable" ]; then

		# update boot
        mount_boot_rw
        sudo sed -i "s;dtparam=audio=on;dtoverlay=pisound;g" /boot/config.txt

        # update alsa config
        sudo sed -i "s/^PERIOD_SIZE=\"1024\"/PERIOD_SIZE=\"128\"/" $HOME/stops/organnery.conf

        echo "pisound enabled, onboard sound disabled for the next session" >> /home/user/organnery.log
        sudo reboot
        
elif [ "$1" = "cursor-disable" ]; then

	sudo sed -i "s/^xserver-command=X -s 0 -dpms$/xserver-command=X -s 0 -dpms -nocursor/" /etc/lightdm/lightdm.conf
	echo "mouse cursor disabled for the next session" >> /home/user/organnery.log

elif [ "$1" = "cursor-enable" ]; then

	sudo sed -i "s/^xserver-command=X -s 0 -dpms -nocursor/xserver-command=X -s 0 -dpms/" /etc/lightdm/lightdm.conf
	echo "mouse cursor enabled for the next session" >> /home/user/organnery.log

elif [ "$1" = "organ-set" ]; then

	source $HOME/stops/organnery.conf
	sudo sed -i "s/^INSTRUMENT_NAME=\"$INSTRUMENT_NAME\"/INSTRUMENT_NAME=\"$2\"/" $HOME/stops/organnery.conf
	echo "Set new active organ to $2 for next reboot" >> /home/user/organnery.log

elif [ "$1" = "organ-switch" ]; then

	source $HOME/stops/organnery.conf
	sudo sed -i "s/^INSTRUMENT_NAME=\"$INSTRUMENT_NAME\"/INSTRUMENT_NAME=\"$2\"/" $HOME/stops/organnery.conf
	killall aeolus
	echo "Switching to new organ $2 now, and set it for next reboot" >> /home/user/organnery.log

elif [ "$1" = "init-usb" ]; then

	echo "Format and fillup usb key with default data" >> /home/user/organnery.log
	# unmount partition
	sudo umount /dev/sda1
	# delete partition table
	sudo dd if=/dev/zero of=/dev/sda bs=512 count=1 conv=notrunc
	# create partitions from template
	sudo /sbin/sfdisk /dev/sda < /usr/share/organnery/data/usbkey.fdk
	# format partitions
	sudo /sbin/mkfs.ext4 -F -L ORGAN /dev/sda1
	sudo /sbin/mkfs.vfat -F 32 -n DATA /dev/sda2
	# copy data
	sudo /usr/share/organnery/organnery-setup
	echo "END usb key format" >> /home/user/organnery.log

else
	echo "ERROR: organnery-config arguments not recognised!" >> /home/user/organnery.log
	echo "ERROR: organnery-config arguments not recognised!"
	echo ""
	echo "usage:"

	echo "organnery-config mount-boot"
	echo "	mount the boot partition as read/write"
	echo ""
	echo "organnery-config overlayfs-check"
	echo "	checks the current overlayfs state"
	echo ""
	echo "organnery-config overlayfs-disable"
	echo "	disables overlayfs for the next session"
	echo ""
	echo "organnery-config overlayfs-enable"
	echo "	enables overlayfs for the next session"
    echo ""
    echo "organnery-config pisound-disable"
    echo "  disables Pisound card and enables onboard sound for the next session"
    echo ""
    echo "organnery-config pisound-enable"
    echo "  enables Pisound card and disables onboard sound for the next session"
    echo ""
    echo "organnery-config cursor-disable"
    echo "  disables mouse cursor for the next session"
    echo ""
    echo "organnery-config cursor-enable"
    echo "  enables mouse cursor for the next session"
    echo ""
    echo "organnery-config organ-set XXX"
    echo "  set XXX as new organ on next reboot"
    echo ""
    echo "organnery-config organ-switch XXX"
    echo "  switch to XXX organ now and save as default"
    echo ""
    echo "organnery-config init-usb"
    echo "  format usb key (sda) and copy organ data for optimal organnery setup"
fi