#!/usr/bin/env bash
#
# a configuration script to modify system parameters
#

OVERLAYFS_CMDLINE="init=/usr/share/organnery/overlayRoot.sh"

# mount the boot partition RW
mount_boot_rw()
{
        sudo umount /boot
        sudo mount /dev/mmcblk0p1 /boot
}

if [ "$1" = "mount-boot" ]; then

	# mount boot partition RW
	mount_boot_rw
	echo "boot partition now mounted rw" 2>&1 | tee -a /home/user/organnery.log

elif [ "$1" = "overlayfs-check" ]; then

	# check whether overlayfs is enabled for the current boot
	if grep -q "$OVERLAYFS_CMDLINE" /proc/cmdline; then
		echo "overlayfs is enabled for current session" 2>&1 | tee -a /home/user/organnery.log
	else
		echo "overlayfs is disabled for current session" 2>&1 | tee -a /home/user/organnery.log
	fi

	# check whether overlayfs is enabled for the next boot
	if grep -q "$OVERLAYFS_CMDLINE" /boot/cmdline.txt; then
		echo "overlayfs is enabled for the next session" 2>&1 | tee -a /home/user/organnery.log
	else
		echo "overlayfs is disabled for the next session" 2>&1 | tee -a /home/user/organnery.log
	fi

elif [ "$1" = "overlayfs-disable" ]; then

	mount_boot_rw
	sudo sed -i "s; $OVERLAYFS_CMDLINE;;g" /boot/cmdline.txt
	echo "overlayfs disabled for the next session" 2>&1 | tee -a /home/user/organnery.log

elif [ "$1" = "overlayfs-enable" ]; then

	if ! grep -q "$OVERLAYFS_CMDLINE" /boot/cmdline.txt; then
		mount_boot_rw
		CMDLINE=`cat /boot/cmdline.txt`
		echo "$CMDLINE $OVERLAYFS_CMDLINE" | sudo tee /boot/cmdline.txt > /dev/null
	fi
	echo "overlayfs enabled for the next session" 2>&1 | tee -a /home/user/organnery.log

elif [ "$1" = "pisound-disable" ]; then

		# update boot
        mount_boot_rw
        sudo sed -i "s;dtoverlay=pisound;dtparam=audio=on;g" /boot/config.txt

        # update alsa config
        sudo sed -i "s/^PERIOD_SIZE=\"128\"/PERIOD_SIZE=\"1024\"/" $HOME/stops/organnery.conf

        echo "pisound disabled, onboard sound enabled for the next session" 2>&1 | tee -a /home/user/organnery.log
        sudo /sbin/reboot

elif [ "$1" = "pisound-enable" ]; then

		# update boot
        mount_boot_rw
        sudo sed -i "s;dtparam=audio=on;dtoverlay=pisound;g" /boot/config.txt

        # update alsa config
        sudo sed -i "s/^PERIOD_SIZE=\"1024\"/PERIOD_SIZE=\"128\"/" $HOME/stops/organnery.conf

        echo "pisound enabled, onboard sound disabled for the next session" 2>&1 | tee -a /home/user/organnery.log
        sudo /sbin/reboot
        
elif [ "$1" = "cursor-disable" ]; then

	sudo sed -i "s/^xserver-command=X -s 0 -dpms$/xserver-command=X -s 0 -dpms -nocursor/" /etc/lightdm/lightdm.conf
	echo "mouse cursor disabled for the next session" 2>&1 | tee -a /home/user/organnery.log

elif [ "$1" = "cursor-enable" ]; then

	sudo sed -i "s/^xserver-command=X -s 0 -dpms -nocursor/xserver-command=X -s 0 -dpms/" /etc/lightdm/lightdm.conf
	echo "mouse cursor enabled for the next session" 2>&1 | tee -a /home/user/organnery.log

elif [ "$1" = "organ-set" ]; then

	source $HOME/stops/organnery.conf
	sudo sed -i "s/^INSTRUMENT_NAME=\"$INSTRUMENT_NAME\"/INSTRUMENT_NAME=\"$2\"/" $HOME/stops/organnery.conf
	echo "Set new active organ to $2 for next reboot" 2>&1 | tee -a /home/user/organnery.log

elif [ "$1" = "organ-switch" ]; then

	source $HOME/stops/organnery.conf
	sudo sed -i "s/^INSTRUMENT_NAME=\"$INSTRUMENT_NAME\"/INSTRUMENT_NAME=\"$2\"/" $HOME/stops/organnery.conf
	killall aeolus
	echo "Switching to new organ $2 now, and set it for next reboot" 2>&1 | tee -a /home/user/organnery.log

elif [ "$1" = "init-usb" ]; then

	echo "Format usb key with default partition scheme" 2>&1 | tee -a /home/user/organnery.log
	# unmount partition
	sudo umount /dev/sda1
	# delete partition table
	sudo dd if=/dev/zero of=/dev/sda bs=512 count=1000 conv=notrunc
	# create partitions from template
	sudo /sbin/sfdisk /dev/sda < /usr/share/organnery/data/usbkey.fdk
	# format partitions
	sudo /sbin/mkfs.ext4 -F -L ORGAN /dev/sda1
	sudo /sbin/mkfs.vfat -F 32 -n DATA /dev/sda2
	echo "END usb key format" 2>&1 | tee -a /home/user/organnery.log
	# reboot
	sudo /sbin/reboot

elif [ "$1" = "ip" ]; then
	if [ "$2" = "dhcp" ]; then
		# enable dhcp
		sudo sed -i "s/iface eth0 inet static/iface eth0 inet dhcp/" /etc/network/interfaces
		# disable static ip lines if not already commented out
		sudo sed -i 's/^[^#].*address.*/#&/' /etc/network/interfaces
		sudo sed -i 's/^[^#].*gateway.*/#&/' /etc/network/interfaces
		sudo /sbin/reboot
	elif [ "$2" = "default" ]; then
		# enable static
		sudo sed -i "s/iface eth0 inet dhcp/iface eth0 inet static/" /etc/network/interfaces
		# set default fixed ip
		sudo sed -i 's/#\{0,1\}.*address.*/ address 192.168.0.100//' /etc/network/interfaces
		sudo sed -i 's/#\{0,1\}.*gateway.*/ gateway 192.168.0.1/' /etc/network/interfaces
		sudo /sbin/reboot
	elif [[ "$2" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
		if [[ "$3" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
			# enable static
			sudo sed -i "s/iface eth0 inet dhcp/iface eth0 inet static/" /etc/network/interfaces
			# set manual fixed ip
			sudo sed -i 's/#\{0,1\}.*address.*/ address $2/' /etc/network/interfaces
			sudo sed -i 's/#\{0,1\}.*gateway.*/ gateway $3/' /etc/network/interfaces
			sudo /sbin/reboot
		else
			echo "ERROR: organnery-config IP argument $3 is not a valid gateway address!" 2>&1 | tee -a /home/user/organnery.log
		fi
	else
		echo "ERROR: organnery-config IP argument $2 is not a valid ip address!" 2>&1 | tee -a /home/user/organnery.log
	fi

else
	echo "ERROR: organnery-config arguments not recognised!" 2>&1 | tee -a /home/user/organnery.log
	echo "ERROR: organnery-config arguments not recognised!"
	echo ""
	echo "usage:"

	echo "organnery-config mount-boot"
	echo "	mount the boot partition as read/write"
	echo ""
	echo "organnery-config overlayfs-check"
	echo "	checks the current overlayfs state"
	echo ""
	echo "organnery-config overlayfs-disable"
	echo "	disables overlayfs for the next session"
	echo ""
	echo "organnery-config overlayfs-enable"
	echo "	enables overlayfs for the next session"
    echo ""
    echo "organnery-config pisound-disable"
    echo "  disables Pisound card and enables onboard sound for the next session"
    echo ""
    echo "organnery-config pisound-enable"
    echo "  enables Pisound card and disables onboard sound for the next session"
    echo ""
    echo "organnery-config cursor-disable"
    echo "  disables mouse cursor for the next session"
    echo ""
    echo "organnery-config cursor-enable"
    echo "  enables mouse cursor for the next session"
    echo ""
    echo "organnery-config organ-set XXX"
    echo "  set XXX as new organ on next reboot"
    echo ""
    echo "organnery-config organ-switch XXX"
    echo "  switch to XXX organ now and save as default"
    echo ""
    echo "organnery-config init-usb"
    echo "  format usb key (sda) and copy organ data for optimal organnery setup"
    echo ""
    echo "organnery-config ip XXX YYY"
    echo "  use either fixed or dhcp ip address, examples :"
    echo "    set to dhcp :"
    echo "  	organnery-config ip dhcp"
    echo "    set to default (ip=192.168.0.100/gw=192.168.0.1) :"
    echo "  	organnery-config ip default"
    echo "    set manual ip/gw :"
    echo "  	organnery-config ip 192.168.1.15 192.168.1.1"
fi