#!/usr/bin/env bash
echo "organnery-setup" | tee -a $HOME/organnery.log

# set cpu governor to performance
cpufreq-set -r -g performance

# set output to 100% on analogue jack if onboard sound enabled
if cat /boot/config.txt | grep -q dtparam=audio=on; then
    amixer cset numid=1 100%
    amixer cset numid=3 1
fi

# simple automount script
MEDIA=sda1
DATA=sda2
USERNAME=user

# quit if no usb drive detected
if ! lsblk | grep $MEDIA; then
    echo "usb not connected! quitting" | tee -a $HOME/organnery.log
    exit 0
fi

# mount the usb drive partition 1 on top of default stops directory
mount /dev/$MEDIA /home/$USERNAME/stops/ -o rw,sync,noatime,noiversion,norelatime
echo "mounted /dev/$MEDIA on /home/$USERNAME/stops/!" | tee -a $HOME/organnery.log

# mount the usb drive partition 2 in ~/usb
if [[ ! -d /home/$USERNAME/usb ]]; then
    mkdir /home/$USERNAME/usb
    chown $USERNAME:$USERNAME /home/$USERNAME/usb
fi
if lsblk | grep $DATA; then
    mount /dev/$DATA /home/$USERNAME/usb/ -o rw,sync,noatime,noiversion,norelatime,uid=1000,gid=1000
    echo "mounted /dev/$DATA on /home/$USERNAME/usb/!" | tee -a $HOME/organnery.log
fi

# TODO check mount is done and stops folder accessible or next test will fail

# if usb drive contains no instrument files, copy defaults to it
if [[ ! $(ls /home/$USERNAME/stops/*.ae0) ]]; then
    # copy stops and instrument definitions
    cp -r /usr/share/organnery/data/stops/* /home/$USERNAME/stops/
    echo "copied instrument files to /dev/$MEDIA!" | tee -a $HOME/organnery.log
else
     echo "existing instrument files found on /dev/$MEDIA!" | tee -a $HOME/organnery.log
fi

# copy presets
if [ ! -f /home/$USERNAME/stops/.aeolus-presets ]; then
    cp /usr/share/organnery/data/file.aeolus-presets /home/$USERNAME/stops/.aeolus-presets
fi

# copy audio params
if [ ! -f /home/$USERNAME/stops/.aeolus-aparams ]; then
    cp /usr/share/organnery/data/file.aeolus-aparams /home/$USERNAME/stops/.aeolus-aparams
fi

# copy default config to usb drive to make it user modifiable, if it doesn't exist
if [ ! -f /home/$USERNAME/stops/organnery.conf ] ; then
  cp /etc/organnery/organnery.conf /home/$USERNAME/stops/organnery.conf
fi

# fix permissions
chown -R $USERNAME:$USERNAME /home/$USERNAME
chmod -R 664 /home/$USERNAME/stops/*.*
chmod -R 664 /home/$USERNAME/usb/*.*
echo "updated permissions in home/$USERNAME" | tee -a $HOME/organnery.log
