#!/usr/bin/env bash

USERNAME=user

# copy stops
cp -r /usr/share/organnery/data/stops /home/$USERNAME

# copy the matching presets
cp /usr/share/organnery/data/file.aeolus-presets /home/$USERNAME/stops/.aeolus-presets

# copy default organnery config, if it doesn't exist
if [ ! -f /home/$USERNAME/stops/organnery.conf ] ; then
  cp /etc/organnery/organnery.conf /home/$USERNAME/stops/organnery.conf
fi

# check if openbox configuration directory exists
if [ ! -d /home/$USERNAME/.config/openbox ] ; then
  mkdir -p /home/$USERNAME/.config/openbox
fi

# copy openbox configuration file
if [ ! -f /home/$USERNAME/.config/openbox/rc.xml ] ; then
  cp /usr/share/organnery/configs/openbox/rc.xml /home/$USERNAME/.config/openbox/
fi

# copy organnery theme for openbox
if [ ! -d /home/$USERNAME/.themes/organnery/openbox-3 ] ; then
  mkdir -p /home/$USERNAME/.themes/organnery/openbox-3
  cp /usr/share/organnery/configs/openbox/close.xbm /home/$USERNAME/.themes/organnery/openbox-3/
  cp /usr/share/organnery/configs/openbox/themerc /home/$USERNAME/.themes/organnery/openbox-3/
fi

# copy organnery theme font
if [ ! -d /home/$USERNAME/.fonts ] ; then
  mkdir -p /home/$USERNAME/.fonts
  cp /usr/share/organnery/configs/openbox/UnifrakturMaguntia21.ttf /home/$USERNAME/.fonts/
fi

# fix permissions
chown -R $USERNAME:$USERNAME /home/$USERNAME

# start application on boot
if [ ! -f /home/$USERNAME/.config/openbox/autostart.sh ] ; then
cat << EOF > /home/$USERNAME/.config/openbox/autostart.sh
#!/usr/bin/env bash
/usr/share/organnery/organnery &
EOF
	chmod +x /home/$USERNAME/.config/openbox/autostart.sh
	chown $USERNAME:$USERNAME /home/$USERNAME/.config/openbox/autostart.sh
fi

# change password
ENCRYPTED_PASSWORD=`mkpasswd -m sha-512 "user"`
usermod -aG audio $USERNAME
usermod -aG sudo $USERNAME
usermod -p "${ENCRYPTED_PASSWORD}" $USERNAME

# autologin
sed -i "s/^autologin-user=AUTOLOGIN-USER-NOT-CONFIGURED/autologin-user=$USERNAME/" /etc/lightdm/lightdm.conf.d/lightdm-autologin-greeter.conf

# no screensaver
sed -i "s/^#xserver-command=X/xserver-command=X -s 0 -dpms/" /etc/lightdm/lightdm.conf

#DEBHELPER#

exit 0
