#!/usr/bin/env bash

USERNAME=user

# extract stops
tar -xf /usr/share/organnery/data/stops.tar.gz -C /home/$USERNAME

# copy presets
cp /usr/share/organnery/data/file.aeolus-presets /home/$USERNAME/.aeolus-presets

# start application on boot
if [ ! -f /home/$USERNAME/.config/openbox/autostart.sh ] ; then
	mkdir -p /home/$USERNAME/.config/openbox
cat << EOF > /home/$USERNAME/.config/openbox/autostart.sh
#!/usr/bin/env bash
/usr/share/organnery/organnery &
EOF
	chmod +x /home/$USERNAME/.config/openbox/autostart.sh
	chown $USERNAME:$USERNAME /home/$USERNAME/.config/openbox/autostart.sh
fi

# change password
ENCRYPTED_PASSWORD=`mkpasswd -m sha-512 "user"`
usermod -aG audio $USERNAME
usermod -aG sudo $USERNAME
usermod -p "${ENCRYPTED_PASSWORD}" $USERNAME

# autologin
sed -i "s/^autologin-user=AUTOLOGIN-USER-NOT-CONFIGURED/autologin-user=$USERNAME/" /etc/lightdm/lightdm.conf.d/lightdm-autologin-greeter.conf

# no screensaver
sed -i "s/^#xserver-command=X/xserver-command=X -s 0 -dpms/" /etc/lightdm/lightdm.conf

#DEBHELPER#

exit 0
